/*
 * File generated by SourceCombiner.exe using 2 source files.
 * Created On: 5/27/2022 10:52:44 PM
*/
using GameSolution;
using System;
using System.Collections;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Numerics;
using System.Text;
//*** SourceCombiner -> original file Pascal.cs ***
namespace GameSolution
{
    public class Pascal
    {
        public List<BigInteger[]> Triangle;
        public Pascal()
        {
            Triangle = new List<BigInteger[]>();
        }
        public long CountTriangleOptimized(long rows, long maxColumn, long divisor)
        {
            Console.Error.WriteLine("Optimized:");
            long counter = 0;
            long multiplier = 1;
            List<long> counters = new List<long>();
            for(int i =0; i < rows; i++)
            {
                if((rows / (long)Math.Pow(divisor, i)) > 0)
                {
                    counters.Add(1);
                }
            }
            for (int r = 0; r < rows; r++)
            {
                multiplier = 1;
                for (int c = 0; c<counters.Count;c++)
                {
                    multiplier *= Math.Min(counters[c], maxColumn);
                    if (c == 0)
                    {
                        counters[c]++;
                    }
                    if(c >= 1 && counters[c-1] == divisor + 1)
                    {
                        counters[c-1] = 1;
                        counters[c]++;
                    }
                }
                Console.Error.WriteLine(" " + multiplier);
                counter += multiplier;
            }
            return counter;
        }
        public long CountTriangle(long rows, long maxColumn, long divisor)
        {
            long counter = 0;
            for(int r = 0; r<rows; r++)
            {
                long mc = Math.Min(maxColumn, r + 1);
                long rowCount = 0;
                for (int c = 0; c< mc; c++)
                {
                    if(Triangle[r][c] % (ulong)divisor != 0)
                    {
                        rowCount++;
                        counter++;
                        counter%=1000000007;
                    }
                }
                Console.Error.WriteLine(" " + rowCount);
            }
            return counter;
        }
        public void BuildTriangle(long rows)
        {
            if (rows == 1)
            {
                Triangle.Add(new BigInteger[1]);
                Triangle[0][0] = 1;
            }
            else
            {
                for(int i = 0; i<rows; i++)
                {
                    Triangle.Add(new BigInteger[i+1]);
                    for(int j = 0; j<i+1; j++)
                    {
                        if (j == 0 || j == i)
                            Triangle[i][j] = 1;
                        else Triangle[i][j] = Triangle[i - 1][j - 1] + Triangle[i - 1][j];
                    }
                }
            }
        }
    }
}
//*** SourceCombiner -> original file Player.cs ***
/**
 * Auto-generated code below aims at helping you parse
 * the standard input according to the problem statement.
 **/
class Solution
{
    static void Main(string[] args)
    {
        int T = int.Parse(Console.ReadLine());
        long[] P, R, C;
        P = new long[T];
        R = new long[T];
        C = new long[T];
        long maximumRows = 0;
        for (int i = 0; i < T; i++)
        {
            string[] inputs = Console.ReadLine().Split(' ');
            P[i] = long.Parse(inputs[0]);
            R[i] = long.Parse(inputs[1]);
            C[i] = long.Parse(inputs[2]);
            maximumRows = Math.Max(maximumRows, R[i]);
            Console.Error.WriteLine(P[i] + " " + R[i] + " " + C[i]);
        }
        Pascal pascal = new Pascal();
        //pascal.BuildTriangle(maximumRows);
        for (int i = 0; i < T; i++)
        {   
            Console.WriteLine(pascal.CountTriangleOptimized(R[i], C[i], P[i]));
        }
    }
}
